# This is a basic workflow to help you get started with Actions

name: Build and Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Angular Full CI
        # You may pin to the exact commit or the version.
        # uses: colbyhill21/angular-full-ci@a3489087f6a715db335078f999c01d422a254a6c
        uses: colbyhill21/angular-full-ci@v1.0
        with:
          # Command to run tests on your project, do not prepend with "npm", it is already included.
          testcommand: test
          # Set to true in order to run mocha tests. This option will install mocha on the image.
          mocha: false  # optional
